### ISSUE TITLE
Feature Request: Implement column width and order remembering using state property

### ISSUE THREAD

**Issue by iworklee** [rtdui/rtdui#1]
Dear Author,

I would like to express my appreciation for the excellent work you have done with rtdui, a great open-source library. The DataTable component is feature-rich and performs well, making it a valuable tool for developers.

I have a small issue that I would like to bring to your attention. I was wondering if it is possible to implement a feature that allows the DataTable component to remember the column widths and order using the existing state property. This would be a great addition to the library and would greatly enhance its usability.

Additionally, it would be even better if this feature could be showcased in the documentation examples. This would help other developers understand how to use this feature effectively.

Thank you for considering my request. I look forward to seeing this feature implemented in the future releases of rtdui.

Best regards

**Comment by rtdui** [comment]
The DataTable component has a `state` controlled prop and an `on[state]Change` callback prop, which gives you complete freedom to control how the state is stored when it changes, as you require:

```js
const [columnOrder, setColumnOrder] = React.useState(localStorage.getItem("my_column_order") ?? []);
const [columnSizing, setColumnSizing] = React.useState(localStorage.getItem("my_column_sizing") ?? {});

const onColumnOrderChange = (updater) => {
  //get new state value
  const newValue = updater instanceof Function ? updater(columnOrder) : updater
  //do something with the new sorting value, e.g.:
  localStorage.setItem("my_column_order", JSON.stringify(newValue))
  setColumnOrder(updater) //normal state update
};

const onColumnSizingChange = (updater) => {
  //get new state value
  const newValue = updater instanceof Function ? updater(columnSizing) : updater
  //do something with the new sorting value, e.g.:
  localStorage.setItem("my_column_sizing", JSON.stringify(newValue))
  setColumnSizing(updater) //normal state update
};

// ...
<DataTable state={{columnOrder, columnSizing}} onColumnOrderChange={onColumnOrderChange} onColumnSizingChange={onColumnSizingChange} ... />
```

Anyway, thanks for your interest and advice.

**Comment by iworklee** [comment]
Thank you for your detailed response! It really helped me。
